name: CI

run-name: Automation is starting

on: push

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy-page
        with:
          v: 1.0.0
          path: ./docs/.vitepress/dist